### ISSUE TITLE
`Gem::Package::FormatError` from `gem compare nokogiri 1.15.5 1.16.0`

### ISSUE THREAD

**Issue by dentarg** [dentarg/gem-compare#10]
Can this be avoided?

```
root@96988add13f7:/app# gem compare nokogiri 1.15.5 1.16.0
Fetching nokogiri-1.15.5.gem
Fetching nokogiri-1.16.0-aarch64-linux.gem
ERROR:  While executing gem ... (Gem::Package::FormatError)
    No such file or directory @ rb_sysopen - /tmp/d20231229-3450-45ud6d/nokogiri-1.16.0.gem
	/usr/local/lib/ruby/3.3.0/rubygems/package.rb:634:in `rescue in verify'
	/usr/local/lib/ruby/3.3.0/rubygems/package.rb:612:in `verify'
	/usr/local/lib/ruby/3.3.0/rubygems/package.rb:597:in `spec'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:289:in `use_package'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:233:in `download_package'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:221:in `get_package'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:83:in `block in compare_versions'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:81:in `each'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:81:in `compare_versions'
	/usr/local/bundle/gems/gem-compare-1.2.1/lib/rubygems/commands/compare_command.rb:100:in `execute'
	/usr/local/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
	/usr/local/lib/ruby/3.3.0/rubygems/command_manager.rb:254:in `invoke_command'
	/usr/local/lib/ruby/3.3.0/rubygems/command_manager.rb:193:in `process_args'
	/usr/local/lib/ruby/3.3.0/rubygems/command_manager.rb:151:in `run'
	/usr/local/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
	/usr/local/bin/gem:12:in `<main>'
```

**Comment by dentarg** [comment]
This is https://github.com/fedora-ruby/gem-compare/issues/37

**Comment by dentarg** [comment]
GitHub Actions has problem running `gem compare sqlite3 2.1.1 2.2.0` at https://github.com/dentarg/kartonger/actions/runs/11609727887/job/32361518173, I re-ran the build but it failed 20 times in a row both times. Full log at https://gist.github.com/dentarg/c637e2bdcae7fcd927ce5076e4f3b508

Meanwhile, I had no problems locally in Docker:

```shell
$ docker run --rm -it ruby:3.3.5 bash
Unable to find image 'ruby:3.3.5' locally
3.3.5: Pulling from library/ruby
c1e0ef7b956a: Pull complete
95b894d63c77: Pull complete
cb5594266b1b: Pull complete
59d4884f8528: Pull complete
d2c0a1b0b203: Pull complete
fb997acfe815: Pull complete
e47444b519e7: Pull complete
Digest: sha256:bceec7582aaa80630bb51a04e2df3af658e64c0640c174371776928ad3bd57b4
Status: Downloaded newer image for ruby:3.3.5
root@5d6995d0fe55:/# gem install gem-compare
Fetching gem-compare-1.2.1.gem
Fetching rainbow-3.1.1.gem
Fetching gemnasium-parser-0.1.9.gem
Fetching diffy-3.4.3.gem
Successfully installed rainbow-3.1.1
Successfully installed gemnasium-parser-0.1.9
Successfully installed diffy-3.4.3
Successfully installed gem-compare-1.2.1
4 gems installed

A new release of RubyGems is available: 3.5.16 → 3.5.22!
Run `gem update --system 3.5.22` to update your installation.

root@5d6995d0fe55:/# gem compare sqlite3 2.1.1 2.2.0
Fetching sqlite3-2.1.1.gem
Fetching sqlite3-2.2.0.gem
Compared versions: ["2.1.1", "2.2.0"]
  DIFFERENT date:
    2.1.1: 2024-10-22 00:00:00 UTC
    2.2.0: 2024-10-30 00:00:00 UTC
  DIFFERENT require_paths:
    2.1.1: ["/usr/local/bundle/extensions/aarch64-linux/3.3.0/sqlite3-2.1.1", "lib"]
    2.2.0: ["/usr/local/bundle/extensions/aarch64-linux/3.3.0/sqlite3-2.2.0", "lib"]
  DIFFERENT rubygems_version:
    2.1.1: 3.5.22
    2.2.0: 3.3.22
  DIFFERENT version:
    2.1.1: 2.1.1
    2.2.0: 2.2.0
  DIFFERENT files:
    2.1.1->2.2.0:
      * Changed:
            CHANGELOG.md +12/-0
            ext/sqlite3/exception.c +71/-66
            ext/sqlite3/exception.h +2/-0
            ext/sqlite3/extconf.rb +6/-3
            ext/sqlite3/statement.c +1/-1
            lib/sqlite3/errors.rb +28/-0
            lib/sqlite3/version.rb +1/-1
  DIFFERENT extra_rdoc_files:
    2.1.1->2.2.0:
      * Changed:
            CHANGELOG.md +12/-0
            ext/sqlite3/exception.c +71/-66
            ext/sqlite3/statement.c +1/-1
root@5d6995d0fe55:/#
```

**Comment by dentarg** [comment]
Looks like using Ruby 3.3.5 helped: https://github.com/dentarg/kartonger/actions/runs/11620804968/job/32363335724

**Comment by dentarg** [comment]
Let's hope it has been solved by newer Ruby/RubyGems versions and doesn't come back and haunt us.
