### ISSUE TITLE
Problem when binary only gems in diff? / `sqlite3` `Gem::Package::FormatError`

### ISSUE THREAD

**Issue by dentarg** [dentarg/gem-compare#14]
From https://github.com/dentarg/kartonger/pull/12 ([patch](https://patch-diff.githubusercontent.com/raw/dentarg/kartonger/pull/12.patch))

```diff
From a9171a69d4f8f13743833eb2eca2d2cc5701b49a Mon Sep 17 00:00:00 2001
From: "dependabot[bot]" <49699333+dependabot[bot]@users.noreply.github.com>
Date: Tue, 26 Nov 2024 09:39:06 +0000
Subject: [PATCH] Bump sqlite3 from 2.2.0 to 2.3.1

Bumps [sqlite3](https://github.com/sparklemotion/sqlite3-ruby) from 2.2.0 to 2.3.1.
- [Release notes](https://github.com/sparklemotion/sqlite3-ruby/releases)
- [Changelog](https://github.com/sparklemotion/sqlite3-ruby/blob/main/CHANGELOG.md)
- [Commits](https://github.com/sparklemotion/sqlite3-ruby/compare/v2.2.0...v2.3.1)

---
updated-dependencies:
- dependency-name: sqlite3
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>
---
 Gemfile.lock | 20 ++++++++++----------
 1 file changed, 10 insertions(+), 10 deletions(-)

diff --git a/Gemfile.lock b/Gemfile.lock
index 8450363..ae0c489 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -231,16 +231,16 @@ GEM
       rubocop-rails
     ruby-progressbar (1.13.0)
     securerandom (0.3.2)
-    sqlite3 (2.2.0-aarch64-linux-gnu)
-    sqlite3 (2.2.0-aarch64-linux-musl)
-    sqlite3 (2.2.0-arm-linux-gnu)
-    sqlite3 (2.2.0-arm-linux-musl)
-    sqlite3 (2.2.0-arm64-darwin)
-    sqlite3 (2.2.0-x86-linux-gnu)
-    sqlite3 (2.2.0-x86-linux-musl)
-    sqlite3 (2.2.0-x86_64-darwin)
-    sqlite3 (2.2.0-x86_64-linux-gnu)
-    sqlite3 (2.2.0-x86_64-linux-musl)
+    sqlite3 (2.3.1-aarch64-linux-gnu)
+    sqlite3 (2.3.1-aarch64-linux-musl)
+    sqlite3 (2.3.1-arm-linux-gnu)
+    sqlite3 (2.3.1-arm-linux-musl)
+    sqlite3 (2.3.1-arm64-darwin)
+    sqlite3 (2.3.1-x86-linux-gnu)
+    sqlite3 (2.3.1-x86-linux-musl)
+    sqlite3 (2.3.1-x86_64-darwin)
+    sqlite3 (2.3.1-x86_64-linux-gnu)
+    sqlite3 (2.3.1-x86_64-linux-musl)
     stimulus-rails (1.3.4)
       railties (>= 6.0.0)
     stringio (3.1.2)
```

https://github.com/dentarg/kartonger/actions/runs/12027787755/job/33529514194#step:2:224

```
Comparing: sqlite3 2.2.0 ➡ 2.3.1
/home/runner/work/_actions/dentarg/gem-compare/v1/compare_gem_versions:66:in `output_from_with_retries': Command 'with_retries gem compare sqlite3 2.2.0 2.3.1' failed: ERROR:  While executing gem ... (Gem::Package::FormatError) (RuntimeError)
    No such file or directory @ rb_sysopen - /tmp/d20241126-1838-4f1h0n/sqlite3-2.2.0.gem
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/package.rb:633:in `rescue in verify'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/package.rb:611:in `verify'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/package.rb:596:in `spec'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:289:in `use_package'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:233:in `download_package'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:221:in `get_package'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:83:in `block in compare_versions'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:81:in `each'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/comparator.rb:81:in `compare_versions'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/gems/3.3.0/gems/gem-compare-1.2.1/lib/rubygems/commands/compare_command.rb:100:in `execute'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/command_manager.rb:253:in `invoke_command'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
	/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/gem:12:in `<main>'
```

**Comment by dentarg** [comment]
https://rubygems.org/gems/sqlite3/versions

**Comment by dentarg** [comment]
Same for nokogiri ([log in private repo](https://github.com/dentarg/swiss/actions/runs/12132635811/job/33826815190?pr=160#step:2:642)) `gem compare nokogiri 1.16.7 1.16.8`

**Comment by dentarg** [comment]
Likely the fix for this: https://github.com/fedora-ruby/gem-compare/pull/42
